In [1]:
import pandas as pd
import numpy as np
from google.colab import files
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [4]:
df = df.drop(['User ID'], axis=1)
df.head(2)

Gender  Age  EstimatedSalary  Purchased
0   Male   19            19000          0
1   Male   35            20000          0

In [18]:
# Making some values as None
df.loc[[10, 100], 'EstimatedSalary'] = None

In [21]:
df.head(11)

Gender  Age  EstimatedSalary  Purchased
0     Male   19          19000.0          0
1     Male   35          20000.0          0
2   Female   26          43000.0          0
3   Female   27          57000.0          0
4     Male   19          76000.0          0
5     Male   27          58000.0          0
6   Female   27          84000.0          0
7   Female   32         150000.0          1
8     Male   25          33000.0          0
9   Female   35          65000.0          0
10  Female   26              NaN          0

In [22]:
# Importing transformers for preprocessing
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer

In [24]:
# Initializing and transforming using Imputer
imputer = SimpleImputer()
salary = imputer.fit_transform(df[['EstimatedSalary']])

In [9]:
# Initializing and transforming using OneHotEncoder
ohe = OneHotEncoder(drop = 'first', sparse = False)
gender = ohe.fit_transform(df[['Gender']])

In [11]:
# Initializing and transforming using MinMaxScaler
sc_age = MinMaxScaler()
age = sc_age.fit_transform(df[['Age']])

In [25]:
# Initializing and transforming using MinMaxScaler
sc_salary = MinMaxScaler()
# salary = sc_salary.fit_transform(df[['EstimatedSalary']])
salary = sc_salary.fit_transform(salary)

In [26]:
# Joining all variables together 
X = np.hstack((gender, age, salary))

In [27]:
X

array([[1.        , 0.02380952, 0.02962963],
       [1.        , 0.4047619 , 0.03703704],
       [0.        , 0.19047619, 0.20740741],
       ...,
       [0.        , 0.76190476, 0.03703704],
       [1.        , 0.42857143, 0.13333333],
       [0.        , 0.73809524, 0.15555556]])

In [17]:
df['Purchased']

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [28]:
# Importing ColumnTransformer
from sklearn.compose import ColumnTransformer

In [29]:
# Initializing ColumnTransformer to apply different transformations over different columns
transformer = ColumnTransformer(transformers = [
    ('Mean Value Handler', SimpleImputer(), ['EstimatedSalary']), 
    ('Salary Scaling', MinMaxScaler(), ['EstimatedSalary']),
    ('Age Scaling', MinMaxScaler(), ['Age']),
    ('Gender One Hot Encoding', OneHotEncoder(drop = 'first', sparse = False), ['Gender'])
  ]
)

In [34]:
df.head(2)

Gender  Age  EstimatedSalary  Purchased
0   Male   19          19000.0          0
1   Male   35          20000.0          0

In [31]:
X_dummy = transformer.fit_transform(df)

In [33]:
X_dummy

array([[1.90000000e+04, 2.96296296e-02, 2.38095238e-02, 1.00000000e+00],
       [2.00000000e+04, 3.70370370e-02, 4.04761905e-01, 1.00000000e+00],
       [4.30000000e+04, 2.07407407e-01, 1.90476190e-01, 0.00000000e+00],
       ...,
       [2.00000000e+04, 3.70370370e-02, 7.61904762e-01, 0.00000000e+00],
       [3.30000000e+04, 1.33333333e-01, 4.28571429e-01, 1.00000000e+00],
       [3.60000000e+04, 1.55555556e-01, 7.38095238e-01, 0.00000000e+00]])

In [35]:
transformer_1 = ColumnTransformer(transformers = [
    ('Gender One Hot Encoding', OneHotEncoder(drop = 'first', sparse = False), ['Gender']),
    # ('Mean Value Handler', SimpleImputer(), ['EstimatedSalary']), 
    ('Age Scaling', MinMaxScaler(), ['Age']),
    ('Salary Scaling', MinMaxScaler(), ['EstimatedSalary']),
  ]
)

In [36]:
X_dummy_1 = transformer_1.fit_transform(df)

In [37]:
X_dummy_1

array([[1.        , 0.02380952, 0.02962963],
       [1.        , 0.4047619 , 0.03703704],
       [0.        , 0.19047619, 0.20740741],
       ...,
       [0.        , 0.76190476, 0.03703704],
       [1.        , 0.42857143, 0.13333333],
       [0.        , 0.73809524, 0.15555556]])

In [38]:
transformer_2 = ColumnTransformer(transformers = [
    ('Gender One Hot Encoding', OneHotEncoder(drop = 'first', sparse = False), ['Gender']),
    ('Age and Salary Scaling', MinMaxScaler(), ['Age', 'EstimatedSalary'])
  ]
)

In [41]:
transformer_2

ColumnTransformer(transformers=[('Gender One Hot Encoding',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Gender']),
                                ('Age and Salary Scaling', MinMaxScaler(),
                                 ['Age', 'EstimatedSalary'])])

In [39]:
X_dummy_2 = transformer_2.fit_transform(df)

In [46]:
transformer_2.named_transformers_

{'Gender One Hot Encoding': OneHotEncoder(drop='first', sparse=False),
 'Age and Salary Scaling': MinMaxScaler(),
 'remainder': 'drop'}

In [50]:
transformer_2.named_transformers_['Age and Salary Scaling'].n_features_in_

2

In [51]:
# initializing ColumnTransformer by passing multiple columns to one transformer
transformer_3 = ColumnTransformer(transformers = [
    ('Gender One Hot Encoding', OneHotEncoder(drop = 'first', sparse = False), ['Gender']),
    ('Age and Salary Scaling', MinMaxScaler(), ['Age', 'EstimatedSalary'])
  ], remainder = 'passthrough'
)

In [52]:
X_dummy_3 = transformer_3.fit_transform(df)
X_dummy_3

array([[1.        , 0.02380952, 0.02962963, 0.        ],
       [1.        , 0.4047619 , 0.03703704, 0.        ],
       [0.        , 0.19047619, 0.20740741, 0.        ],
       ...,
       [0.        , 0.76190476, 0.03703704, 1.        ],
       [1.        , 0.42857143, 0.13333333, 0.        ],
       [0.        , 0.73809524, 0.15555556, 1.        ]])

In [57]:
# Using make_column_transformer to perform column transformer. We need not pass user defined transformer names explicitly
from sklearn.compose import make_column_transformer
transformer_5 = make_column_transformer(
    (OneHotEncoder(drop = 'first', sparse = False), ['Gender']),
    (MinMaxScaler(), ['Age']),
    (MinMaxScaler(), ['EstimatedSalary']), remainder = 'passthrough'
)

In [58]:
transformer_5.fit_transform(df)

array([[1.        , 0.02380952, 0.02962963, 0.        ],
       [1.        , 0.4047619 , 0.03703704, 0.        ],
       [0.        , 0.19047619, 0.20740741, 0.        ],
       ...,
       [0.        , 0.76190476, 0.03703704, 1.        ],
       [1.        , 0.42857143, 0.13333333, 0.        ],
       [0.        , 0.73809524, 0.15555556, 1.        ]])

In [60]:
from sklearn.compose import make_column_transformer
transformer_6 = make_column_transformer(
    (OneHotEncoder(drop = 'first', sparse = False), [0]),
    (MinMaxScaler(), [1]),
    (MinMaxScaler(), [2]), remainder = 'passthrough'
)
transformer_6.fit_transform(df)

array([[1.        , 0.02380952, 0.02962963, 0.        ],
       [1.        , 0.4047619 , 0.03703704, 0.        ],
       [0.        , 0.19047619, 0.20740741, 0.        ],
       ...,
       [0.        , 0.76190476, 0.03703704, 1.        ],
       [1.        , 0.42857143, 0.13333333, 0.        ],
       [0.        , 0.73809524, 0.15555556, 1.        ]])

In [63]:
df.head(20)

Gender  Age  EstimatedSalary  Purchased
0     Male   19          19000.0          0
1     Male   35          20000.0          0
2   Female   26          43000.0          0
3   Female   27          57000.0          0
4     Male   19          76000.0          0
5     Male   27          58000.0          0
6   Female   27          84000.0          0
7   Female   32         150000.0          1
8     Male   25          33000.0          0
9   Female   35          65000.0          0
10  Female   26              NaN          0
11  Female   26          52000.0          0
12    Male   20          86000.0          0
13    Male   32          18000.0          0
14    Male   18          82000.0          0
15    Male   29          80000.0          0
16    Male   47          25000.0          1
17    Male   45          26000.0          1
18    Male   46          28000.0          1
19  Female   48          29000.0          1

In [59]:
# Pipeline
from sklearn.pipeline import Pipeline, make_pipeline 

In [67]:
# Creating Transformers for applying multiple transformers one after another
transformer_7 = make_column_transformer(
    (OneHotEncoder(drop = 'first', sparse = False), [0]),
    (MinMaxScaler(), [1]),
    (SimpleImputer(), [2]), remainder = 'passthrough'
)

transformer_8 = make_column_transformer(
    (MinMaxScaler(), [2]), remainder = 'passthrough'
)

In [68]:
# Creating pipeline to bind transformers in sequence
pipe = Pipeline(
    [
        ('Imputer Transformer', transformer_7),
        ('Categorical Encoding and MinMaxScaling', transformer_8)
    ]
)

In [77]:
# Creating pipeline with make_pipeline
pipe_1 = make_pipeline(transformer_7, transformer_8)

In [70]:
# Fitting and transforming data using pipeline
pipe.fit_transform(df)

array([[0.02962963, 1.        , 0.02380952, 0.        ],
       [0.03703704, 1.        , 0.4047619 , 0.        ],
       [0.20740741, 0.        , 0.19047619, 0.        ],
       ...,
       [0.03703704, 0.        , 0.76190476, 1.        ],
       [0.13333333, 1.        , 0.42857143, 0.        ],
       [0.15555556, 0.        , 0.73809524, 1.        ]])

In [78]:
pipe_1.fit_transform(df)

array([[0.02962963, 1.        , 0.02380952, 0.        ],
       [0.03703704, 1.        , 0.4047619 , 0.        ],
       [0.20740741, 0.        , 0.19047619, 0.        ],
       ...,
       [0.03703704, 0.        , 0.76190476, 1.        ],
       [0.13333333, 1.        , 0.42857143, 0.        ],
       [0.15555556, 0.        , 0.73809524, 1.        ]])

In [71]:
transformer_7 = make_column_transformer(
    (OneHotEncoder(drop = 'first', sparse = False), [0]),
    (MinMaxScaler(), [1]),
    (SimpleImputer(), [2]), remainder = 'passthrough'
)

transformer_8 = make_column_transformer(
    (MinMaxScaler(), [2]), remainder = 'passthrough'
)

In [73]:
X_dummy = transformer_7.fit_transform(df)

In [76]:
X_dummy

array([[1.00000000e+00, 2.38095238e-02, 1.90000000e+04, 0.00000000e+00],
       [1.00000000e+00, 4.04761905e-01, 2.00000000e+04, 0.00000000e+00],
       [0.00000000e+00, 1.90476190e-01, 4.30000000e+04, 0.00000000e+00],
       ...,
       [0.00000000e+00, 7.61904762e-01, 2.00000000e+04, 1.00000000e+00],
       [1.00000000e+00, 4.28571429e-01, 3.30000000e+04, 0.00000000e+00],
       [0.00000000e+00, 7.38095238e-01, 3.60000000e+04, 1.00000000e+00]])

In [75]:
transformer_8.fit_transform(X_dummy)

array([[0.02962963, 1.        , 0.02380952, 0.        ],
       [0.03703704, 1.        , 0.4047619 , 0.        ],
       [0.20740741, 0.        , 0.19047619, 0.        ],
       ...,
       [0.03703704, 0.        , 0.76190476, 1.        ],
       [0.13333333, 1.        , 0.42857143, 0.        ],
       [0.15555556, 0.        , 0.73809524, 1.        ]])

In [46]:
# Binding Everything together
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier

In [4]:
from google.colab import files
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads (1).csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [6]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [10]:
# Dropping User ID
df = df.drop(('User ID'), axis=1)

In [11]:
# Separating Input and Output
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [14]:
# Splitting data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0, stratify = y)

In [26]:
# Initializing transformers for the input to Pipeline
transformer_1 = ColumnTransformer(
    [
        ('One Hot Cat Encoding', OneHotEncoder(drop = 'first', sparse = False), [0]),
        ('Age Scaling', MinMaxScaler(), [1]),
        ('Filling Null with Mean', SimpleImputer(), [2])
    ], remainder = 'passthrough'
)

transformer_2 = ColumnTransformer(
    [
        ('Salary Scaling', MinMaxScaler(), [2])
    ], remainder = 'passthrough'
)

model = KNeighborsClassifier()

In [27]:
# Creating Pipeline
pipe = Pipeline([
    ('Transformer 1', transformer_1),
    ('Transformer 2', transformer_2)
])

In [28]:
# Fitting pipe to train data
X_train_transformed = pipe.fit_transform(X_train)
model.fit(X_train_transformed, y_train)

In [30]:
# Getting Prediction on Test Data
X_test_transformed = pipe.transform(X_test)
model.score(X_test_transformed, y_test)

0.9125

In [33]:
# Applying Pipeline with Cross Validation
# Creating Pipeline
pipe = Pipeline([
    ('Transformer 1', transformer_1),
    ('Transformer 2', transformer_2),
    ('Model', model)
])
cv_scores = cross_val_score(pipe, X_train, y_train, cv = 10, n_jobs = -1)

In [34]:
cv_scores

array([0.90625, 0.9375 , 0.96875, 0.90625, 0.9375 , 0.84375, 0.90625,
       0.9375 , 0.875  , 0.875  ])

In [36]:
pipe.named_steps

{'Transformer 1': ColumnTransformer(remainder='passthrough',
                   transformers=[('One Hot Cat Encoding',
                                  OneHotEncoder(drop='first', sparse=False),
                                  [0]),
                                 ('Age Scaling', MinMaxScaler(), [1]),
                                 ('Filling Null with Mean', SimpleImputer(),
                                  [2])]),
 'Transformer 2': ColumnTransformer(remainder='passthrough',
                   transformers=[('Salary Scaling', MinMaxScaler(), [2])]),
 'Model': KNeighborsClassifier()}

In [37]:
pipe.named_steps['Transformer 2']

ColumnTransformer(remainder='passthrough',
                  transformers=[('Salary Scaling', MinMaxScaler(), [2])])

In [39]:
pipe.named_steps['Transformer 2'].transformers

[('Salary Scaling', MinMaxScaler(), [2])]

In [40]:
pipe.named_steps['Transformer 2'].transformers[0]

('Salary Scaling', MinMaxScaler(), [2])

In [41]:
pipe.named_steps['Transformer 2'].transformers[0][1]

MinMaxScaler()

In [44]:
pipe.named_steps['Transformer 2'].transformers[0][1]

MinMaxScaler()

In [50]:
model.get_params().keys()

dict_keys(['algorithm', 'leaf_size', 'metric', 'metric_params', 'n_jobs', 'n_neighbors', 'p', 'weights'])

In [51]:
# Hyper Parameter Tuning with pipeline object
param = [{
    'n_neighbors':[3, 5, 7, 9],
    'p':[1, 2, 3]
}]

In [52]:
model_cv = GridSearchCV(pipe, param_grid=param, cv = 5)
model_cv.fit(X_train, y_train)

ValueError: ignored

In [47]:
help(GridSearchCV)

Help on class GridSearchCV in module sklearn.model_selection._search:

class GridSearchCV(BaseSearchCV)
 |  GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)
 |  
 |  Exhaustive search over specified parameter values for an estimator.
 |  
 |  Important members are fit, predict.
 |  
 |  GridSearchCV implements a "fit" and a "score" method.
 |  It also implements "score_samples", "predict", "predict_proba",
 |  "decision_function", "transform" and "inverse_transform" if they are
 |  implemented in the estimator used.
 |  
 |  The parameters of the estimator used to apply these methods are optimized
 |  by cross-validated grid-search over a parameter grid.
 |  
 |  Read more in the :ref:`User Guide <grid_search>`.
 |  
 |  Parameters
 |  ----------
 |  estimator : estimator object
 |      This is assumed to implement the scikit-learn estimator interface.
 |      Either est

In [ ]:
cv_scores = GridSearchCV(pipe, X_train, y_train, cv = 10, n_jobs = -1)