In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'x1':[1]*100,
    'x2':range(1,101),
    'y':np.arange(1, 101)*2
})

In [3]:
df

x1   x2    y
0    1    1    2
1    1    2    4
2    1    3    6
3    1    4    8
4    1    5   10
..  ..  ...  ...
95   1   96  192
96   1   97  194
97   1   98  196
98   1   99  198
99   1  100  200

[100 rows x 3 columns]

In [4]:
df['x1'].var()

0.0

In [5]:
# Filter Method
from sklearn.feature_selection import SelectKBest, chi2, VarianceThreshold

In [7]:
vt = VarianceThreshold()
vt.fit_transform(df)

array([[  1,   2],
       [  2,   4],
       [  3,   6],
       [  4,   8],
       [  5,  10],
       [  6,  12],
       [  7,  14],
       [  8,  16],
       [  9,  18],
       [ 10,  20],
       [ 11,  22],
       [ 12,  24],
       [ 13,  26],
       [ 14,  28],
       [ 15,  30],
       [ 16,  32],
       [ 17,  34],
       [ 18,  36],
       [ 19,  38],
       [ 20,  40],
       [ 21,  42],
       [ 22,  44],
       [ 23,  46],
       [ 24,  48],
       [ 25,  50],
       [ 26,  52],
       [ 27,  54],
       [ 28,  56],
       [ 29,  58],
       [ 30,  60],
       [ 31,  62],
       [ 32,  64],
       [ 33,  66],
       [ 34,  68],
       [ 35,  70],
       [ 36,  72],
       [ 37,  74],
       [ 38,  76],
       [ 39,  78],
       [ 40,  80],
       [ 41,  82],
       [ 42,  84],
       [ 43,  86],
       [ 44,  88],
       [ 45,  90],
       [ 46,  92],
       [ 47,  94],
       [ 48,  96],
       [ 49,  98],
       [ 50, 100],
       [ 51, 102],
       [ 52, 104],
       [ 53,

In [6]:
help(VarianceThreshold())

Help on VarianceThreshold in module sklearn.feature_selection._variance_threshold object:

class VarianceThreshold(sklearn.feature_selection._base.SelectorMixin, sklearn.base.BaseEstimator)
 |  VarianceThreshold(threshold=0.0)
 |  
 |  Feature selector that removes all low-variance features.
 |  
 |  This feature selection algorithm looks only at the features (X), not the
 |  desired outputs (y), and can thus be used for unsupervised learning.
 |  
 |  Read more in the :ref:`User Guide <variance_threshold>`.
 |  
 |  Parameters
 |  ----------
 |  threshold : float, default=0
 |      Features with a training-set variance lower than this threshold will
 |      be removed. The default is to keep all features with non-zero variance,
 |      i.e. remove the features that have the same value in all samples.
 |  
 |  Attributes
 |  ----------
 |  variances_ : array, shape (n_features,)
 |      Variances of individual features.
 |  
 |  n_features_in_ : int
 |      Number of features seen duri

In [9]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [11]:
fs = SelectKBest(score_func = chi2, k = 1)
fs_fit = fs.fit(X, y)

In [12]:
fs_fit.scores_

array([   0., 1650.])

In [14]:
df

x1   x2    y
0    1    1    2
1    1    2    4
2    1    3    6
3    1    4    8
4    1    5   10
..  ..  ...  ...
95   1   96  192
96   1   97  194
97   1   98  196
98   1   99  198
99   1  100  200

[100 rows x 3 columns]

In [13]:
df.corr()

x1   x2    y
x1 NaN  NaN  NaN
x2 NaN  1.0  1.0
y  NaN  1.0  1.0

In [15]:
from google.colab import files
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [16]:
df1 = pd.read_csv("Social_Network_Ads.csv")

In [19]:
df1.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [20]:
df1['Gender'] = df1['Gender'].map({'Male':1, 'Female':0})

In [21]:
df1.corr()

User ID    Gender       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.025249 -0.000721         0.071097   0.007120
Gender          -0.025249  1.000000 -0.073741        -0.060435  -0.042469
Age             -0.000721 -0.073741  1.000000         0.155238   0.622454
EstimatedSalary  0.071097 -0.060435  0.155238         1.000000   0.362083
Purchased        0.007120 -0.042469  0.622454         0.362083   1.000000

In [22]:
df1.shape

(400, 5)

In [23]:
train = df1.iloc[:-40,:]
test = df1.iloc[-40:,:]

In [25]:
X_train = train.iloc[:, :-1]
y_train = train.iloc[:, -1]

X_test = test.iloc[:, :-1]
y_test = test.iloc[:, -1]

In [27]:
y_train

0      0
1      0
2      0
3      0
4      0
      ..
355    1
356    1
357    0
358    1
359    0
Name: Purchased, Length: 360, dtype: int64

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [31]:
import joblib
import sys
sys.modules['sklearn.externals.joblib'] = joblib

In [32]:
from mlxtend.feature_selection import SequentialFeatureSelector
ffs = SequentialFeatureSelector(model, k_features = 3, scoring = 'accuracy').fit(X_train, y_train)

In [33]:
ffs.k_score_

0.7027777777777777

In [34]:
ffs.k_feature_names_

('Gender', 'Age', 'EstimatedSalary')

In [35]:
# Embedded Method
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [36]:
model.feature_importances_

array([0.10645841, 0.        , 0.35596689, 0.5375747 ])