In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [4]:
df = pd.read_csv("Social_Network_Ads.csv")

In [5]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
df_new = df.drop(['User ID'], axis=1)

In [8]:
df_new

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [9]:
X = df_new.drop(['Purchased'], axis=1)
y = df_new['Purchased']

In [10]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
X

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [ ]:
X

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [12]:
X.iloc[:, 1:]

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [14]:
# Perform train test split on Input data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X.iloc[:, 1:], y, test_size = 0.2, random_state = 0, stratify = y)

In [16]:
X_test

Age  EstimatedSalary
361   53            34000
245   51           146000
313   49           141000
294   35            57000
376   46            74000
..   ...              ...
39    27            31000
164   33            69000
98    35            73000
101   28            59000
364   42           104000

[80 rows x 2 columns]

In [15]:
X_train

Age  EstimatedSalary
213   35            58000
192   29            43000
26    49            28000
195   34            43000
252   48           134000
..   ...              ...
175   23            28000
215   60           108000
64    59            83000
21    47            49000
330   38            51000

[320 rows x 2 columns]

In [20]:
# Fitting Logistic Regression on Age and Estimateds Salary columns as Input
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.6375

In [21]:
# Scaling age and estimated salary using min max scaler
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [22]:
X_train_scaled

array([[0.4047619 , 0.31851852],
       [0.26190476, 0.20740741],
       [0.73809524, 0.0962963 ],
       [0.38095238, 0.20740741],
       [0.71428571, 0.88148148],
       [0.47619048, 0.71851852],
       [0.26190476, 0.0962963 ],
       [0.14285714, 0.08888889],
       [0.5       , 0.41481481],
       [0.42857143, 0.27407407],
       [0.14285714, 0.05925926],
       [0.        , 0.52592593],
       [0.85714286, 0.40740741],
       [0.42857143, 0.28888889],
       [0.80952381, 0.91111111],
       [0.76190476, 0.21481481],
       [0.30952381, 0.54814815],
       [0.78571429, 0.05925926],
       [0.52380952, 0.42222222],
       [0.30952381, 0.41481481],
       [0.30952381, 0.        ],
       [0.04761905, 0.4962963 ],
       [0.95238095, 0.23703704],
       [0.97619048, 0.2       ],
       [0.69047619, 0.72592593],
       [0.92857143, 0.33333333],
       [0.52380952, 0.68148148],
       [0.28571429, 0.48148148],
       [0.64285714, 0.08148148],
       [0.26190476, 0.34074074],
       [0.

In [23]:
# Fitting Logistic Regression on scaled Age and scaled Estimated Salary columns as Input
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
model.score(X_test_scaled, y_test)

0.7875

In [ ]:
y

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [28]:
# Applying One Hot Encoder to Gender Column
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first', sparse = False)
X_train_ohe = ohe.fit_transform(X_train[['Gender']])
X_test_ohe = ohe.transform(X_test[['Gender']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [29]:
X_train_ohe


array([[1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],

In [33]:
X_train.drop(['Gender'], axis = 1)

Age  EstimatedSalary
213   35            58000
192   29            43000
26    49            28000
195   34            43000
252   48           134000
..   ...              ...
175   23            28000
215   60           108000
64    59            83000
21    47            49000
330   38            51000

[320 rows x 2 columns]

In [34]:
# Appending One hot encoded gender column with age and estoimated salary columns to create new dataset
X_train_transformed = np.hstack((X_train_ohe, X_train.drop(['Gender'], axis=1)))
X_test_transformed = np.hstack((X_test_ohe, X_test.drop(['Gender'], axis=1)))

In [35]:
X_train_transformed

array([[1.00e+00, 3.50e+01, 5.80e+04],
       [1.00e+00, 2.90e+01, 4.30e+04],
       [1.00e+00, 4.90e+01, 2.80e+04],
       [1.00e+00, 3.40e+01, 4.30e+04],
       [0.00e+00, 4.80e+01, 1.34e+05],
       [0.00e+00, 3.80e+01, 1.12e+05],
       [0.00e+00, 2.90e+01, 2.80e+04],
       [0.00e+00, 2.40e+01, 2.70e+04],
       [0.00e+00, 3.90e+01, 7.10e+04],
       [1.00e+00, 3.60e+01, 5.20e+04],
       [1.00e+00, 2.40e+01, 2.30e+04],
       [0.00e+00, 1.80e+01, 8.60e+04],
       [1.00e+00, 5.40e+01, 7.00e+04],
       [0.00e+00, 3.60e+01, 5.40e+04],
       [0.00e+00, 5.20e+01, 1.38e+05],
       [0.00e+00, 5.00e+01, 4.40e+04],
       [0.00e+00, 3.10e+01, 8.90e+04],
       [1.00e+00, 5.10e+01, 2.30e+04],
       [0.00e+00, 4.00e+01, 7.20e+04],
       [0.00e+00, 3.10e+01, 7.10e+04],
       [0.00e+00, 3.10e+01, 1.50e+04],
       [0.00e+00, 2.00e+01, 8.20e+04],
       [0.00e+00, 5.80e+01, 4.70e+04],
       [0.00e+00, 5.90e+01, 4.20e+04],
       [0.00e+00, 4.70e+01, 1.13e+05],
       [1.00e+00, 5.70e+0

In [36]:
# Fitting Logistic Regression on Ohe gender, Age and Estimateds Salary columns as Input
model = LogisticRegression()
model.fit(X_train_transformed, y_train)
model.score(X_test_transformed, y_test)

0.6375

In [37]:
sc = MinMaxScaler()
X_train_scaled_new = sc.fit_transform(X_train_transformed)
X_test_scaled_new = sc.transform(X_test_transformed)

In [ ]:
X_train_scaled_new

In [40]:
# Fitting Logistic Regression on Ohe Gender and scaled Age and scaled Estimateds Salary columns as Input
model = LogisticRegression()
model.fit(X_train_scaled_new, y_train)
model.score(X_test_scaled_new, y_test)

0.7875

In [41]:
# Applying One Hot Encoder to Gender Column
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
X_train_ohe = oe.fit_transform(X_train[['Gender']])
X_test_ohe = oe.transform(X_test[['Gender']])

In [42]:
X_train_transformed = np.hstack((X_train_ohe, X_train.drop(['Gender'], axis=1)))
X_test_transformed = np.hstack((X_test_ohe, X_test.drop(['Gender'], axis=1)))

In [43]:
X_train_transformed

array([[1.00e+00, 3.50e+01, 5.80e+04],
       [1.00e+00, 2.90e+01, 4.30e+04],
       [1.00e+00, 4.90e+01, 2.80e+04],
       [1.00e+00, 3.40e+01, 4.30e+04],
       [0.00e+00, 4.80e+01, 1.34e+05],
       [0.00e+00, 3.80e+01, 1.12e+05],
       [0.00e+00, 2.90e+01, 2.80e+04],
       [0.00e+00, 2.40e+01, 2.70e+04],
       [0.00e+00, 3.90e+01, 7.10e+04],
       [1.00e+00, 3.60e+01, 5.20e+04],
       [1.00e+00, 2.40e+01, 2.30e+04],
       [0.00e+00, 1.80e+01, 8.60e+04],
       [1.00e+00, 5.40e+01, 7.00e+04],
       [0.00e+00, 3.60e+01, 5.40e+04],
       [0.00e+00, 5.20e+01, 1.38e+05],
       [0.00e+00, 5.00e+01, 4.40e+04],
       [0.00e+00, 3.10e+01, 8.90e+04],
       [1.00e+00, 5.10e+01, 2.30e+04],
       [0.00e+00, 4.00e+01, 7.20e+04],
       [0.00e+00, 3.10e+01, 7.10e+04],
       [0.00e+00, 3.10e+01, 1.50e+04],
       [0.00e+00, 2.00e+01, 8.20e+04],
       [0.00e+00, 5.80e+01, 4.70e+04],
       [0.00e+00, 5.90e+01, 4.20e+04],
       [0.00e+00, 4.70e+01, 1.13e+05],
       [1.00e+00, 5.70e+0

In [ ]:
# Cross Validation Techniques
# 1. K Fold Cross Validation
import numpy as np
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Importing packages
from sklearn.model_selection import KFold, RepeatedKFold, StratifiedKFold, RepeatedStratifiedKFold

In [ ]:
# Initialize KFold
kfold = KFold(n_splits = 5) 
list(kfold.split(a))

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [ ]:
# Initialize RepeatedKFold
rkfold = RepeatedKFold(n_splits = 5, n_repeats=2, random_state = 0) 
list(rkfold.split(a))

[(array([0, 1, 3, 4, 5, 6, 7, 9]), array([2, 8])),
 (array([0, 1, 2, 3, 5, 6, 7, 8]), array([4, 9])),
 (array([0, 2, 3, 4, 5, 7, 8, 9]), array([1, 6])),
 (array([0, 1, 2, 4, 5, 6, 8, 9]), array([3, 7])),
 (array([1, 2, 3, 4, 6, 7, 8, 9]), array([0, 5])),
 (array([0, 1, 2, 4, 6, 7, 8, 9]), array([3, 5])),
 (array([0, 3, 4, 5, 6, 7, 8, 9]), array([1, 2])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9])),
 (array([1, 2, 3, 4, 5, 7, 8, 9]), array([0, 6])),
 (array([0, 1, 2, 3, 5, 6, 8, 9]), array([4, 7]))]

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.random.randint(0, 2, 10)

In [ ]:
b

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
# Initialize StratifiedKFold
skfold = StratifiedKFold()
list(skfold.split(a, b))

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


[(array([1, 2, 3, 5, 6, 7, 8, 9]), array([0, 4])),
 (array([0, 2, 3, 4, 6, 7, 8, 9]), array([1, 5])),
 (array([0, 1, 3, 4, 5, 7, 8, 9]), array([2, 6])),
 (array([0, 1, 2, 4, 5, 6, 8, 9]), array([3, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [ ]:
skfold = StratifiedKFold(n_splits = 4)
list(skfold.split(a, b))

[(array([2, 3, 5, 6, 7, 8, 9]), array([0, 1, 4])),
 (array([0, 1, 3, 4, 7, 8, 9]), array([2, 5, 6])),
 (array([0, 1, 2, 4, 5, 6, 8, 9]), array([3, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [ ]:
b = np.array([0, 1, 1, 1, 0, 1, 0, 0, 1, 0])

In [ ]:
skfold = StratifiedKFold(n_splits = 5)
list(skfold.split(a, b))

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 3, 5, 6, 7, 8, 9]), array([2, 4])),
 (array([0, 1, 2, 4, 5, 7, 8, 9]), array([3, 6])),
 (array([0, 1, 2, 3, 4, 6, 8, 9]), array([5, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [ ]:
# Initialize RepeatedStratifiedKFold
rskfold = RepeatedStratifiedKFold(n_splits = 5, n_repeats=2)
list(rskfold.split(a, b))

[(array([0, 1, 2, 4, 5, 6, 8, 9]), array([3, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9])),
 (array([0, 2, 3, 5, 6, 7, 8, 9]), array([1, 4])),
 (array([1, 3, 4, 5, 6, 7, 8, 9]), array([0, 2])),
 (array([0, 1, 2, 3, 4, 7, 8, 9]), array([5, 6])),
 (array([0, 2, 3, 4, 5, 6, 8, 9]), array([1, 7])),
 (array([0, 1, 2, 3, 4, 7, 8, 9]), array([5, 6])),
 (array([0, 1, 2, 5, 6, 7, 8, 9]), array([3, 4])),
 (array([0, 1, 3, 4, 5, 6, 7, 8]), array([2, 9])),
 (array([1, 2, 3, 4, 5, 6, 7, 9]), array([0, 8]))]

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df_new = df.drop(['User ID'], axis=1)
df_new

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [ ]:
X = df_new.iloc[:, :-1]
y = df_new.iloc[:, -1]

In [ ]:
# Split Data into Training and Testing Part
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [ ]:
# Importing OneHotEncoder and MinMaxScaler
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

In [ ]:
# Initialize OneHotEncoder
ohe = OneHotEncoder(drop = 'first', sparse = False)
X_train_gender = ohe.fit_transform(X_train[['Gender']])
X_test_gender = ohe.transform(X_test[['Gender']])

In [ ]:
# Append transformed gender with age and salary to make it as input data
X_train_t = np.hstack((X_train_gender, X_train.drop('Gender', axis=1)))
X_test_t = np.hstack((X_test_gender, X_test.drop('Gender', axis=1)))

In [ ]:
# Initialize and fitting scaler
sc = MinMaxScaler()
X_train_scaled = sc.fit_transform(X_train_t)
X_test_scaled = sc.transform(X_test_t)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train_scaled, y_train)
model.score(X_test_scaled, y_test)

0.9125

In [ ]:
X_scaled = np.vstack((X_train_scaled, X_test_scaled))

In [ ]:
X_new = X.copy()
X_new['Gender'] = X_new['Gender'].replace({'Male':0, 'Female':1})

In [ ]:
X_new_scaled = sc.fit_transform(X_new)

In [ ]:
from sklearn.model_selection import cross_val_score
model = KNeighborsClassifier()
cv = cross_val_score(model, X_new_scaled, y, cv = 10)

In [ ]:
cv

array([1.   , 0.825, 0.925, 0.975, 1.   , 0.825, 0.825, 0.825, 0.875,
       1.   ])

In [ ]:
cv.mean()

0.9075

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [ ]:
param = [{
    'n_neighbors':[3, 5, 7, 9],
    'p':[1, 2, 3]
}]

In [ ]:
model_cv = GridSearchCV(model, param_grid=param, cv = 5)
model_cv.fit(X_new_scaled, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': [3, 5, 7, 9], 'p': [1, 2, 3]}])

In [ ]:
print(model_cv.best_params_)

{'n_neighbors': 9, 'p': 3}


In [ ]:
print(model_cv.best_score_)

0.9075


In [ ]:
model = KNeighborsClassifier(n_neighbors = 9, p = 3)
cv = cross_val_score(model, X_new_scaled, y, cv = 10)
cv

array([1.   , 0.85 , 0.9  , 0.975, 0.975, 0.85 , 0.825, 0.825, 0.875,
       1.   ])

In [ ]:
cv.mean()

0.9075

In [ ]:
model_cv = GridSearchCV(model, param_grid=param, cv = 5, verbose = 4)
model_cv.fit(X_new_scaled, y)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END ................n_neighbors=3, p=1;, score=0.912 total time=   0.0s
[CV 2/5] END ................n_neighbors=3, p=1;, score=0.925 total time=   0.0s
[CV 3/5] END ................n_neighbors=3, p=1;, score=0.887 total time=   0.0s
[CV 4/5] END ................n_neighbors=3, p=1;, score=0.812 total time=   0.0s
[CV 5/5] END ................n_neighbors=3, p=1;, score=0.800 total time=   0.0s
[CV 1/5] END ................n_neighbors=3, p=2;, score=0.912 total time=   0.0s
[CV 2/5] END ................n_neighbors=3, p=2;, score=0.912 total time=   0.0s
[CV 3/5] END ................n_neighbors=3, p=2;, score=0.887 total time=   0.0s
[CV 4/5] END ................n_neighbors=3, p=2;, score=0.800 total time=   0.0s
[CV 5/5] END ................n_neighbors=3, p=2;, score=0.812 total time=   0.0s
[CV 1/5] END ................n_neighbors=3, p=3;, score=0.912 total time=   0.0s
[CV 2/5] END ................n_neighbors=3, p=3;

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9, p=3),
             param_grid=[{'n_neighbors': [3, 5, 7, 9], 'p': [1, 2, 3]}],
             verbose=4)

In [ ]:
model_cv = GridSearchCV(model, param_grid=param, cv = 5, n_jobs = -1)
model_cv.fit(X_new_scaled, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9, p=3),
             n_jobs=-1,
             param_grid=[{'n_neighbors': [3, 5, 7, 9], 'p': [1, 2, 3]}])

In [ ]:
model_cv = RandomizedSearchCV(model, param_distributions=param, cv = 5, n_iter = 3, verbose = 4)
model_cv.fit(X_new_scaled, y)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV 1/5] END ................n_neighbors=5, p=3;, score=0.900 total time=   0.0s
[CV 2/5] END ................n_neighbors=5, p=3;, score=0.938 total time=   0.0s
[CV 3/5] END ................n_neighbors=5, p=3;, score=0.887 total time=   0.0s
[CV 4/5] END ................n_neighbors=5, p=3;, score=0.825 total time=   0.0s
[CV 5/5] END ................n_neighbors=5, p=3;, score=0.863 total time=   0.0s
[CV 1/5] END ................n_neighbors=9, p=2;, score=0.912 total time=   0.0s
[CV 2/5] END ................n_neighbors=9, p=2;, score=0.938 total time=   0.0s
[CV 3/5] END ................n_neighbors=9, p=2;, score=0.900 total time=   0.0s
[CV 4/5] END ................n_neighbors=9, p=2;, score=0.838 total time=   0.0s
[CV 5/5] END ................n_neighbors=9, p=2;, score=0.938 total time=   0.0s
[CV 1/5] END ................n_neighbors=3, p=1;, score=0.912 total time=   0.0s
[CV 2/5] END ................n_neighbors=3, p=1;,

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9, p=3),
                   n_iter=3,
                   param_distributions=[{'n_neighbors': [3, 5, 7, 9],
                                         'p': [1, 2, 3]}],
                   verbose=4)

In [ ]:
model_cv.best_params_

{'p': 2, 'n_neighbors': 9}

In [ ]:
model_cv.best_score_

0.905

In [ ]:
help(RandomizedSearchCV)

Help on class RandomizedSearchCV in module sklearn.model_selection._search:

class RandomizedSearchCV(BaseSearchCV)
 |  RandomizedSearchCV(estimator, param_distributions, *, n_iter=10, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', random_state=None, error_score=nan, return_train_score=False)
 |  
 |  Randomized search on hyper parameters.
 |  
 |  RandomizedSearchCV implements a "fit" and a "score" method.
 |  It also implements "score_samples", "predict", "predict_proba",
 |  "decision_function", "transform" and "inverse_transform" if they are
 |  implemented in the estimator used.
 |  
 |  The parameters of the estimator used to apply these methods are optimized
 |  by cross-validated search over parameter settings.
 |  
 |  In contrast to GridSearchCV, not all parameter values are tried out, but
 |  rather a fixed number of parameter settings is sampled from the specified
 |  distributions. The number of parameter settings that are tried is
 |  