In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [ ]:
df = pd.read_csv("Social_Network_Ads.csv")

In [ ]:
df = df.drop(['User ID'], axis=1)

In [ ]:
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [ ]:
X = df.drop(['Purchased'], axis=1)
y = df.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first', sparse = False)
X_train_ohe = ohe.fit_transform(X_train[['Gender']])
X_test_ohe = ohe.transform(X_test[['Gender']])

In [ ]:
X_train_new = np.hstack((X_train_ohe, X_train.drop(['Gender'], axis=1)))
X_test_new = np.hstack((X_test_ohe, X_test.drop(['Gender'], axis=1)))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train_ohe, y_train)

DecisionTreeClassifier()

In [ ]:
model.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [ ]:
model.score(X_train_ohe, y_train), model.score(X_test_ohe, y_test)

(0.64375, 0.6375)

In [ ]:
model.feature_importances_

array([1.])

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train_new, y_train)

DecisionTreeClassifier()

In [ ]:
model.score(X_train_new, y_train), model.score(X_test_new, y_test)

(1.0, 0.9)

In [ ]:
model.feature_importances_

array([0.03815364, 0.50672977, 0.45511659])

In [ ]:
# Fitting model on age and estimated salary
model = DecisionTreeClassifier()
model.fit(X_train.iloc[:, 1:], y_train)

DecisionTreeClassifier()

In [ ]:
model.score(X_train.iloc[:, 1:], y_train), model.score(X_test.iloc[:, 1:], y_test)

(0.996875, 0.8625)

In [ ]:
# Training model with Cross Validation
model_1 = DecisionTreeClassifier()
cv_scores = cross_val_score(model_1, X_train_new, y_train, cv = 10, n_jobs=-1)

In [ ]:
cv_scores, cv_scores.mean()

(array([0.875  , 0.90625, 0.875  , 0.9375 , 0.875  , 0.84375, 0.8125 ,
        0.84375, 0.8125 , 0.84375]), 0.8625)

In [ ]:
model_1.fit(X_train_new, y_train)
model_1.score(X_train_new, y_train), model_1.score(X_test_new, y_test)

(1.0, 0.8875)

In [ ]:
# Cross Validation with stratification
model_1 = DecisionTreeClassifier()
cv = StratifiedKFold(n_splits = 10)
cv_scores = cross_val_score(model_1, X_train_new, y_train, cv = cv, n_jobs=-1)

In [ ]:
cv_scores, cv_scores.mean()

(array([0.875  , 0.875  , 0.875  , 0.9375 , 0.875  , 0.84375, 0.84375,
        0.875  , 0.8125 , 0.84375]), 0.865625)

In [ ]:
# Decision Tree Regression
from sklearn.datasets import load_boston
boston = load_boston()
X = boston['data']
y = boston['target']

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor 
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [ ]:
model.score(X_train, y_train), model.score(X_test, y_test)

(1.0, 0.6045703926388948)